import Header from '@/Components/Header'
import Footer from '@/Components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR">
      <body className="flex flex-col gap-8">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
